platform:ios,'8.0'
target 'LETimberExam'do
pod 'Masonry','~> 1.0.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'AFNetworking','~> 3.1.0'
pod 'MJExtension','~> 3.0.13'
pod 'IQKeyboardManager','~> 3.3.7'
pod 'UITableView+FDTemplateLayoutCell', '1.4'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'SDCycleScrollView','~> 1.64'
pod 'YYText', '~> 1.0.5'
end
